version: '3.4'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=odc
      - POSTGRES_USER=odc
      - POSTGRES_PASSWORD=AnInsecurePassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  opendatacube:
    image: csiroeasi/easi-training-pc:latest
    depends_on:
      - postgres
    environment:
      - DISPLAY
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - ../datacube-core:/home/jovyan/odc
      - ../../sample_data:/data
      - ../output:/home/jovyan/output
      - ../work:/home/jovyan/work
      - ./config/datacube.conf:/home/jovyan/.datacube.conf
    
    stdin_open: true
    tty: true

volumes: 
  postgres-data:
    name: easi-training-pc-postgres-data
