version: '3.4'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=odc
      - POSTGRES_USER=odc
      - POSTGRES_PASSWORD=eev2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  opendatacube:
    image: csiroeasi/easi-training-pc:latest
    depends_on:
      - postgres
    environment:
      - DISPLAY
    ports:
     - "8888:8888"
    volumes:
      - ../datacube-core:/home/jovyan/odc
      - ../../sample_data:/data
      - ../output:/home/jovyan/output
      - ../work:/home/jovyan/work
      - ./config/datacube.conf:/home/jovyan/.datacube.conf
      - ./config/datacube_integration.conf:/home/jovyan/.datacube_integration.conf
    
    stdin_open: true
    tty: true

volumes: 
  postgres-data:
    name: easi-training-pc-postgres-data
